language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0

env:
    - SYMFONY_BRANCH=propel SYMFONY_REPOSITORY=https://github.com/rozwell/symfony1.git

before_script:
    - ./prepare_tests.sh

script: php mockproject/plugins/sfPropelORMPlugin/test/bin/prove.php
